import { totals, type ReportEntry } from './domain';
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
const xml=(v:unknown)=>String(v??'').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
function column(n:number){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
export async function createExcelBlob(rows:ReportEntry[],scope:string){
  const {default:JSZip}=await import('jszip');const zip=new JSZip(),t=totals(rows);
  const sheets=[
    {name:'Resumo',widths:[42,32],data:[['Confraternização do 4º Pelotão','26/10/2026'],['Local','Clube LED · Cordeiros-BA'],['Filtro',scope],['Policiais confirmados',t.confirmed],['Policiais ausentes',t.absent],['Convidados',t.guests],['Total de participantes',t.participants],['Gerado em',new Date().toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})]]},
    {name:'Respostas',widths:[40,20,25,22,15,65,24],data:[['Nome do policial','Matrícula','Município de lotação','Presença','Convidados','Nomes dos convidados','Última atualização'],...rows.map(r=>[r.name,r.registration,r.municipality,r.attending?'Confirmada':'Ausência',r.guests.length,r.guests.join('; '),new Date(r.updatedAt!).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})])]},
    {name:'Convidados',widths:[40,20,25,12,40],data:[['Policial responsável','Matrícula','Município de lotação','Número','Nome do convidado'],...rows.filter(r=>r.attending).flatMap(r=>r.guests.map((n,i)=>[r.name,r.registration,r.municipality,i+1,n]))]},
  ];
  zip.file('[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`);
  zip.file('_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
  zip.file('xl/workbook.xml',`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${s.name}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`);
  zip.file('xl/_rels/workbook.xml.rels',`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`);
  zip.file('xl/styles.xml','<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF122D40"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"><alignment vertical="top" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>');
  sheets.forEach((s,i)=>zip.file(`xl/worksheets/sheet${i+1}.xml`,`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${s.widths.map((w,j)=>`<col min="${j+1}" max="${j+1}" width="${w}" customWidth="1"/>`).join('')}</cols><sheetData>${s.data.map((row,r)=>`<row r="${r+1}"${r===0?' ht="32" customHeight="1"':''}>${row.map((v,c)=>typeof v==='number'?`<c r="${column(c)}${r+1}" s="${r===0?1:0}"><v>${v}</v></c>`:`<c r="${column(c)}${r+1}" t="inlineStr" s="${r===0?1:0}"><is><t xml:space="preserve">${xml(v)}</t></is></c>`).join('')}</row>`).join('')}</sheetData>${i>0?`<autoFilter ref="A1:${column(s.widths.length-1)}${s.data.length}"/>`:''}</worksheet>`));
  return await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',compression:'DEFLATE'});
}
export async function exportExcel(rows:ReportEntry[],scope:string){download(await createExcelBlob(rows,scope),'confraternizacao-4-pelotao.xlsx');}
export async function createPDFDocument(rows:ReportEntry[],scope:string){
  const [{jsPDF},{default:autoTable}]=await Promise.all([import('jspdf'),import('jspdf-autotable')]);const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),t=totals(rows);
  doc.setFillColor(18,45,64);doc.rect(0,0,297,34,'F');doc.setTextColor(255,255,255);doc.setFontSize(19);doc.text('Confraternização do 4º Pelotão',14,16);doc.setFontSize(10);doc.text('26 de outubro de 2026 · Clube LED · Cordeiros-BA',14,25);doc.setTextColor(35,57,72);doc.setFontSize(10);const lines=doc.splitTextToSize(`Filtro: ${scope}`,269);doc.text(lines,14,44);const y=44+lines.length*5;doc.text(`Confirmados: ${t.confirmed}     Ausentes: ${t.absent}     Convidados: ${t.guests}     Participantes: ${t.participants}`,14,y+5);
  autoTable(doc,{startY:y+12,head:[['Policial / matrícula','Município','Presença','Qtd. convidados','Convidados']],body:rows.length?rows.map(r=>[`${r.name}\nMatrícula: ${r.registration}`,r.municipality,r.attending?'Confirmada':'Ausência',r.guests.length,r.guests.length?r.guests.map((n,i)=>`${i+1}. ${n}`).join('\n'):'—']):[['Nenhuma resposta no filtro atual.','','','','']],theme:'striped',headStyles:{fillColor:[18,45,64],textColor:[255,255,255],fontSize:9},styles:{fontSize:9,cellPadding:3,overflow:'linebreak',textColor:[35,57,72]},columnStyles:{0:{cellWidth:72},1:{cellWidth:40},2:{cellWidth:30},3:{cellWidth:27},4:{cellWidth:100}},margin:{left:14,right:14,top:15,bottom:19},rowPageBreak:'avoid'});
  const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setFontSize(8);doc.setTextColor(105,123,136);doc.text(`Gerado em ${new Date().toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}`,14,201);doc.text(`Página ${i} de ${pages}`,283,201,{align:'right'});}return doc;
}
export async function exportPDF(rows:ReportEntry[],scope:string){const doc=await createPDFDocument(rows,scope);doc.save('confraternizacao-4-pelotao.pdf');}

