'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { UsersRound, UserCheck, UserX, FileSpreadsheet, FileText, RefreshCw, ClipboardList, LoaderCircle } from 'lucide-react';
import { EventSidebar } from './components';
import { totals, type ReportEntry } from './domain';
import { exportExcel, exportPDF } from './exports';
function filterRows(rows:ReportEntry[],town:string,status:string,search:string){return rows.filter(r=>(!town||r.municipality===town)&&(!status||(status==='yes'?r.attending:!r.attending))&&(!search||`${r.name} ${r.registration} ${r.guests.join(' ')}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))));}
import { readAdmin, supabase } from './api';
export default function Admin({email}:{email:string}){
  const [rows,setRows]=useState<ReportEntry[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[town,setTown]=useState(''),[status,setStatus]=useState(''),[search,setSearch]=useState(''),[updated,setUpdated]=useState(''),[exporting,setExporting]=useState('');
  const active=useRef<Promise<ReportEntry[]>|null>(null);
  const refresh=useCallback(async()=>{if(active.current)return active.current;setRefreshing(true);const task=(async()=>{try{const data=await readAdmin();setRows(data.entries);setUpdated(data.refreshedAt);setError('');return data.entries;}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar dados.');throw e;}finally{setLoading(false);setRefreshing(false);active.current=null;}})();active.current=task;return task;},[]);
  useEffect(()=>{void refresh().catch(()=>{});const timer=setInterval(()=>void refresh().catch(()=>{}),30000);const onFocus=()=>void refresh().catch(()=>{});window.addEventListener('focus',onFocus);return()=>{clearInterval(timer);window.removeEventListener('focus',onFocus);};},[refresh]);
  const townRows=filterRows(rows,town,'',''),t=totals(townRows),filtered=filterRows(rows,town,status,search),towns=[...new Set(rows.map(r=>r.municipality))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
  const scope=[town||'Todos os municípios',status==='yes'?'Somente confirmados':status==='no'?'Somente ausentes':'Todas as respostas',search?`Busca: ${search}`:''].filter(Boolean).join(' · ');
  async function runExport(format:'Excel'|'PDF'){setExporting(format);try{const latest=await refresh();const data=filterRows(latest,town,status,search);await(format==='Excel'?exportExcel(data,scope):exportPDF(data,scope));}catch(e){setError(e instanceof Error?e.message:'Não foi possível exportar. Tente novamente.');}finally{setExporting('');}}
  return <div className="app-shell admin-shell"><EventSidebar admin/><main className="admin-main"><header className="topbar"><span>ÁREA DOS ORGANIZADORES</span><span className="account-info">{email} · <button className="text-button" onClick={()=>void supabase?.auth.signOut()}>Sair</button></span></header><div className="admin-container"><div className="admin-heading"><div><span className="eyebrow">CONFRATERNIZAÇÃO 2026</span><h2>Painel de presenças</h2><p className="lead">Acompanhe as confirmações e planeje o nosso encontro.</p></div><div className="export-actions"><button className="secondary" disabled={loading||!!exporting} onClick={()=>void runExport('Excel')}>{exporting==='Excel'?<LoaderCircle size={17} className="spin"/>:<FileSpreadsheet size={17}/>}Excel</button><button className="secondary" disabled={loading||!!exporting} onClick={()=>void runExport('PDF')}>{exporting==='PDF'?<LoaderCircle size={17} className="spin"/>:<FileText size={17}/>}PDF</button></div></div>
  <div className="metrics" aria-live="polite">{[{label:'Policiais confirmados',value:t.confirmed,icon:UserCheck,note:'Presença no encontro'},{label:'Policiais ausentes',value:t.absent,icon:UserX,note:'Não comparecerão'},{label:'Convidados',value:t.guests,icon:UsersRound,note:'Acompanhantes informados'},{label:'Total de participantes',value:t.participants,icon:UsersRound,note:'Policiais + convidados'}].map((m,i)=><section className={'metric '+(i===3?'total':'')} key={m.label}><span className="metric-label">{m.label}<m.icon size={18}/></span><strong>{loading?'—':m.value}</strong><small>{m.note}</small></section>)}</div>
  {error&&<div className="error report-error" role="alert">{error}</div>}<section className="report-card"><div className="print-report"><h1>Confraternização do 4º Pelotão</h1><p>26/10/2026 · Clube LED · Cordeiros-BA</p></div><div className="report-top"><div><h3>Relação de policiais e convidados</h3><small>{rows.length} {rows.length===1?'resposta registrada':'respostas registradas'}</small></div><button className="refresh-button" disabled={refreshing} onClick={()=>void refresh().catch(()=>{})}><RefreshCw size={15} className={refreshing?'spin':''}/>Atualizar</button></div>
  {error&&updated&&<p className="offline-stale">Mostrando os dados da última atualização bem-sucedida.</p>}<div className="filters"><label className="filter-field">Município de lotação<select value={town} onChange={e=>setTown(e.target.value)}><option value="">Todos os municípios</option>{towns.map(n=><option key={n} value={n}>{n}</option>)}</select></label><label className="filter-field">Presença<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todas as respostas</option><option value="yes">Confirmados</option><option value="no">Ausentes</option></select></label><label className="filter-field search">Buscar policial ou convidado<input type="search" placeholder="Nome ou matrícula" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="report-meta"><span>{filtered.length} {filtered.length===1?'resposta exibida':'respostas exibidas'} · Indicadores por município</span><span>{updated?`Atualizado às ${new Date(updated).toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo'})}`:'Aguardando atualização'}</span></div>
  {loading?<div className="loading" role="status"><LoaderCircle size={21} className="spin"/>Carregando respostas…</div>:filtered.length?<div className="table-wrap"><table><thead><tr><th>Policial</th><th>Município</th><th>Presença</th><th>Convidados</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>Matrícula {r.registration}</small><small>{new Date(r.updatedAt!).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small></td><td>{r.municipality}</td><td><span className={'tag '+(r.attending?'yes':'no')}>{r.attending?'Confirmada':'Ausência'}</span></td><td className="table-guests">{r.guests.length?<>{r.guests.map((n,i)=><span key={i}>{String(i+1).padStart(2,'0')} · {n}</span>)}<small>{r.guests.length} {r.guests.length===1?'convidado':'convidados'}</small></>:<span>Sem convidados</span>}</td></tr>)}</tbody></table></div>:<div className="empty-state"><ClipboardList size={36}/><h3>{rows.length?'Nenhuma resposta neste filtro':'Aguardando as primeiras respostas'}</h3><p>{rows.length?'Ajuste os filtros para consultar outros policiais.':'Assim que os policiais responderem, as confirmações e os convidados aparecerão aqui.'}</p></div>}</section><p className="admin-note">Atualização automática a cada 30 segundos. Excel e PDF incluem a relação conforme os filtros selecionados. Não há prazo limite para respostas ou alterações.</p><footer className="form-footer"><span>4º Pelotão · Organização da confraternização</span><span>26.10.2026</span></footer></div></main></div>;
}

