'use client';
import { useEffect, useRef, useState } from 'react';
import { Check, CheckCircle2, UserRound, UsersRound, ClipboardCheck, Copy, CircleHelp, LoaderCircle, Pencil, Minus, Plus } from 'lucide-react';
import { EventSidebar, Summary } from './components';
import { responseSchema, type Entry } from './domain';
type Draft={name:string;registration:string;municipality:string;attending:boolean|null;bringGuests:boolean|null;guests:string[];version:number};
const empty:Draft={name:'',registration:'',municipality:'',attending:null,bringGuests:null,guests:[],version:0};
import { request, resetPersonalSession } from './api';
export default function RSVP(){
  const [draft,setDraft]=useState<Draft>(empty),[step,setStep]=useState(1),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<Entry|null>(null),[editToken,setEditToken]=useState(''),[copied,setCopied]=useState(false),[countText,setCountText]=useState('1');
  const titleRef=useRef<HTMLHeadingElement>(null);
  const update=(values:Partial<Draft>)=>setDraft(d=>({...d,...values}));
  async function load(){setLoading(true);setError('');try{
    const token=new URLSearchParams(window.location.hash.slice(1)).get('edit');
    if(token){await request('/api/session',{method:'POST',body:JSON.stringify({token})});window.history.replaceState(null,'',window.location.pathname);}
    const data=await request('/api/me');
    if(data.entry){const e=data.entry as Entry;setDraft({...e,bringGuests:e.guests.length>0});setReceipt(e);setEditToken(data.editToken);setCountText(String(Math.max(1,e.guests.length)));}
  }catch(e){setError(e instanceof Error?e.message:'Falha ao carregar sua resposta.');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  useEffect(()=>{if(!loading)titleRef.current?.focus();},[step,receipt,loading]);
  useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{void Promise.resolve(context.registerTool({name:'read_rsvp_summary',title:'Consultar resumo da confirmação',description:'Lê a resposta registrada ou o rascunho visível, sem enviar nem alterar a confirmação.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Não informe parâmetros.');const e=receipt||draft;return {saved:!!receipt,name:e.name,municipality:e.municipality,attending:e.attending,guests:e.guests};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[receipt,draft]);
  function go(next:number){setError('');if(next===2&&step===1){if(draft.name.trim().length<3){setError('Informe o nome completo do policial.');return;}if(!/^\d{4,20}$/.test(draft.registration)){setError('Informe a matrícula com 4 a 20 dígitos.');return;}if(draft.municipality.trim().length<2){setError('Informe o município de lotação.');return;}}
    if(next===3){if(draft.attending===null){setError('Selecione se você confirma sua presença.');return;}if(draft.attending&&draft.bringGuests===null){setError('Informe se pretende levar convidados.');return;}if(draft.attending&&draft.bringGuests&&(!/^\d+$/.test(countText)||Number(countText)<1||Number(countText)>100)){setError('Informe uma quantidade de 1 a 100 convidados.');return;}const result=responseSchema.safeParse(toEntry());if(!result.success){setError(result.error.issues[0].path[0]==='guests'?'Preencha o nome de todos os convidados.':result.error.issues[0].message);return;}}
    setStep(next);
  }
  function toEntry():Entry{return {name:draft.name.trim(),registration:draft.registration,municipality:draft.municipality.trim(),attending:draft.attending===true,guests:draft.attending&&draft.bringGuests?draft.guests.map(n=>n.trim()):[],version:draft.version};}
  function resize(value:string){setCountText(value);const n=Number(value);if(Number.isInteger(n)&&n>=1&&n<=100)setDraft(d=>({...d,guests:Array.from({length:n},(_,i)=>d.guests[i]||'')}));}
  async function save(){if(busy)return;setBusy(true);setError('');try{const data=await request('/api/me',{method:'PUT',body:JSON.stringify(toEntry())});setReceipt(data.entry);setEditToken(data.editToken);setDraft(d=>({...d,...data.entry}));}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
  const link=()=>`${window.location.origin}${window.location.pathname}#edit=${editToken}`;
  async function copy(){try{await navigator.clipboard.writeText(link());setCopied(true);setTimeout(()=>setCopied(false),3000);}catch{setError('Copie o link pessoal no campo abaixo.');}}
  return <div className="app-shell"><EventSidebar/><main className="form-main"><header className="topbar"><span>CONFIRMAÇÃO DE PRESENÇA</span><span className="open-badge">Inscrições abertas</span></header><div className="form-container">
    {loading?<div className="loading" role="status"><LoaderCircle className="spin"/>Carregando o formulário…</div>:receipt?<>
      <div className="success-icon"><CheckCircle2 size={34}/></div><span className="eyebrow">RESPOSTA REGISTRADA</span><h2 ref={titleRef} tabIndex={-1}>{receipt.attending?'Presença confirmada!':'Ausência registrada.'}</h2><p className="lead">{receipt.attending?'Esperamos você no nosso encontro.':'Obrigado por informar à organização.'}</p>
      <section className="form-card"><div className="card-title"><ClipboardCheck size={22}/><h3>Sua confirmação</h3></div><Summary entry={receipt}/><div className="receipt-date">Atualizada em {new Date(receipt.updatedAt!).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</div></section>
      <section className="link-card"><h3>Guarde seu link pessoal</h3><p>Com ele, você pode alterar a presença e os convidados em qualquer dispositivo, sem login. Este link é exclusivo para editar sua resposta.</p><div className="copy-row"><input aria-label="Link pessoal de atualização" readOnly value={typeof window==='undefined'?'':link()}/><button type="button" className="secondary" onClick={copy}><Copy size={17}/>{copied?'Copiado':'Copiar'}</button></div></section>
      {error&&<div role="alert" className="error">{error}</div>}<div className="export-actions"><button className="primary" onClick={()=>{setReceipt(null);setStep(1);setError('');}}><Pencil size={17}/>Atualizar minha resposta</button><button className="secondary" onClick={()=>{resetPersonalSession();setReceipt(null);setDraft(empty);setEditToken('');setStep(1);setCountText('1');setError('');}}>Preencher para outro policial</button></div>
    </>:<><span className="eyebrow">CONFRATERNIZAÇÃO 2026</span><h2 ref={titleRef} tabIndex={-1}>{draft.version?'Atualize sua confirmação':'Confirme sua presença'}</h2><p className="lead">Preencha seus dados e informe quem vem com você.</p>
      <ol className="steps" aria-label="Etapas do formulário">{[{label:'Identificação',icon:UserRound},{label:'Presença',icon:UsersRound},{label:'Revisão',icon:ClipboardCheck}].map((s,i)=><li key={s.label} className={step===i+1?'active':step>i+1?'done':''} aria-current={step===i+1?'step':undefined}><span className="step-circle">{step>i+1?<Check size={17}/>:i+1}</span><span>{s.label}</span></li>)}</ol>
      <form className="form-card" onSubmit={e=>{e.preventDefault();step===3?void save():go(step+1);}}>
        <div className="card-title">{step===1?<UserRound size={22}/>:step===2?<UsersRound size={22}/>:<ClipboardCheck size={22}/>}<h3>{step===1?'Identificação do policial':step===2?'Sua participação':'Confira sua resposta'}</h3><span className="step-meta">{String(step).padStart(2,'0')} / 03</span></div>
        {step===1?<><label className="field" htmlFor="name">Nome completo do policial <span>*</span><input id="name" autoComplete="name" required minLength={3} maxLength={160} placeholder="Digite seu nome completo" value={draft.name} onChange={e=>update({name:e.target.value})}/></label><div className="field-grid"><label className="field" htmlFor="registration">Matrícula <span>*</span><input id="registration" inputMode="numeric" pattern="[0-9]{4,20}" maxLength={20} required readOnly={draft.version>0} placeholder="Somente números" value={draft.registration} onChange={e=>update({registration:e.target.value.replace(/\D/g,'')})}/></label><label className="field" htmlFor="municipality">Município de lotação <span>*</span><input id="municipality" required minLength={2} maxLength={100} autoComplete="address-level2" list="towns" placeholder="Informe o município" value={draft.municipality} onChange={e=>update({municipality:e.target.value})}/><datalist id="towns"><option>Cordeiros</option><option>Condeúba</option><option>Piripá</option></datalist></label></div><p className="field-note"><CircleHelp size={16}/>A matrícula identifica sua resposta e evita duplicidades.</p></>:step===2?<>
          <fieldset><legend>Você confirma sua presença na confraternização do 4º Pelotão, no dia 26/10/2026? <span>*</span></legend><div className="choices"><label className={'choice '+(draft.attending===true?'selected':'')}><input type="radio" name="presence" required checked={draft.attending===true} onChange={()=>update({attending:true})}/><div><strong>Sim, confirmo minha presença.</strong><small>Vou participar do encontro.</small></div></label><label className={'choice '+(draft.attending===false?'selected':'')}><input type="radio" name="presence" required checked={draft.attending===false} onChange={()=>update({attending:false,bringGuests:false,guests:[]})}/><div><strong>Não poderei comparecer.</strong><small>Informar minha ausência à organização.</small></div></label></div></fieldset>
          {draft.attending===true&&<div className="guests-section"><fieldset><legend>Você pretende levar convidados para o evento? <span>*</span></legend><div className="small-choices"><label className={'choice '+(draft.bringGuests===true?'selected':'')}><input type="radio" name="guests" required checked={draft.bringGuests===true} onChange={()=>{update({bringGuests:true,guests:draft.guests.length?draft.guests:['']});setCountText(String(Math.max(1,draft.guests.length)));}}/>Sim</label><label className={'choice '+(draft.bringGuests===false?'selected':'')}><input type="radio" name="guests" required checked={draft.bringGuests===false} onChange={()=>update({bringGuests:false,guests:[]})}/>Não</label></div></fieldset>
            {draft.bringGuests===true&&<><label className="field" htmlFor="quantity">Quantidade de convidados <span>*</span><div className="quantity-control"><button type="button" aria-label="Diminuir convidados" disabled={Number(countText)<=1} onClick={()=>resize(String(Number(countText)-1))}><Minus size={18}/></button><input id="quantity" type="number" min={1} max={100} required value={countText} onChange={e=>resize(e.target.value)}/><button type="button" aria-label="Aumentar convidados" disabled={Number(countText)>=100} onClick={()=>resize(String(Number(countText)+1))}><Plus size={18}/></button></div></label><div className="guest-fields">{draft.guests.map((name,i)=><label className="field" key={i} htmlFor={'guest-'+i}>Convidado {String(i+1).padStart(2,'0')} <span>*</span><input id={'guest-'+i} required minLength={3} maxLength={160} placeholder="Nome completo do convidado" value={name} onChange={e=>update({guests:draft.guests.map((n,j)=>i===j?e.target.value:n)})}/></label>)}</div><p className="field-note">Todos os convidados informados precisam ter o nome preenchido.</p></>}
          </div>}{draft.attending===false&&<p className="info-box">Você não precisará preencher convidados. Revise os seus dados e registre a ausência na próxima etapa.</p>}
        </>:<><p className="review-note">Confira os dados antes de registrar. Você poderá atualizá-los depois pelo seu link pessoal.</p><Summary entry={toEntry()}/></>}
        {error&&<div className="error" role="alert">{error}</div>}<div className="form-actions">{step>1?<button type="button" className="secondary" onClick={()=>go(step-1)} disabled={busy}>Voltar</button>:<span className="required-note">* Campos obrigatórios</span>}<button className="primary" type="submit" disabled={busy}>{busy?<><LoaderCircle size={17} className="spin"/>Registrando…</>:step===3?<><Check size={18}/>{draft.attending?'Confirmar participação':'Registrar ausência'}</>:step===2?'Revisar resposta':'Continuar'}</button></div>
      </form><p className="privacy-note"><span>Sem login ou senha.</span> Após o envio, guarde o link pessoal para atualizar sua resposta. Não há prazo limite para alterações.</p>
      {error&&loading===false&&step===1&&<button className="text-button" type="button" onClick={()=>void load()}>Recarregar minha resposta</button>}
    </>}
    <footer className="form-footer"><span>4º Pelotão · Cordeiros-BA</span><span>26.10.2026</span></footer>
  </div></main></div>;
}

